version: 0.2
env:
  variables:
    AWS_REGION: eu-west-2
phases:  # Fixed spelling
  install:
    runtime-versions:
      java: corretto8
    commands:
      # Get CodeArtifact token - FIXED COMMAND
      - export CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain nextwork --domain-owner 185847269562 --region $AWS_REGION --query authorizationToken --output text)
      - echo "TOKEN_HEAD: ${CODEARTIFACT_AUTH_TOKEN:0:10}..."

      # Generate settings.xml
      - >
        cat > settings.xml << 'EOF'
        <settings>
          <servers>
            <server>
              <id>codeartifact</id>
              <username>aws</username>
              <password>${env.CODEARTIFACT_AUTH_TOKEN}</password>
            </server>
          </servers>
          <mirrors>
            <mirror>
              <id>codeartifact-mirror</id>
              <url>https://nextwork-185847269562.d.codeartifact.eu-west-2.amazonaws.com/maven/nextwork-devops-cicd/</url>
              <mirrorOf>central</mirrorOf>
            </mirror>
          </mirrors>
        </settings>
        EOF

      # Debug: Verify settings.xml
      - cat settings.xml

  build:
    commands:
      - mvn clean install -s settings.xml -Denv.CODEARTIFACT_AUTH_TOKEN="$CODEARTIFACT_AUTH_TOKEN" -B -e -X | tee mvn.log
